create extension if not exists "pgcrypto";

create table profiles (id uuid primary key references auth.users on delete cascade, display_name text, role text not null default 'user' check (role in ('user','owner','admin')), home_location text, home_latitude double precision, home_longitude double precision, created_at timestamptz default now());
create table places (id uuid primary key default gen_random_uuid(), owner_id uuid references profiles(id), name text not null, category text not null check (category in ('cafe','food')), address text not null, latitude double precision not null, longitude double precision not null, description text, parking boolean default false, public_parking boolean default false, cozy boolean default false, quiet boolean default false, quiet_times text[] default '{}', reservable boolean default false, created_at timestamptz default now());
create table visits (user_id uuid references profiles(id) on delete cascade, place_id uuid references places(id) on delete cascade, visited_at timestamptz default now(), primary key(user_id,place_id));
create table reports (id uuid primary key default gen_random_uuid(), user_id uuid references profiles(id), place_id uuid references places(id), parking boolean, cozy boolean, quiet boolean, quiet_time text, note text, status text default 'pending' check(status in ('pending','approved','rejected')), created_at timestamptz default now());
create table coupons (id uuid primary key default gen_random_uuid(), place_id uuid references places(id) on delete cascade, owner_id uuid references profiles(id), title text not null, condition text, expires_on date not null, active boolean default true, created_at timestamptz default now());
create table bookings (id uuid primary key default gen_random_uuid(), place_id uuid references places(id), user_id uuid references profiles(id), guest_name text not null, booked_for timestamptz not null, party_size int not null check(party_size between 1 and 20), note text, status text default 'pending' check(status in ('pending','confirmed','completed','cancelled')), created_at timestamptz default now());
create table menus (id uuid primary key default gen_random_uuid(), place_id uuid references places(id) on delete cascade, name text not null, price integer not null check(price >= 0), image_url text, active boolean default true, sort_order integer default 0);
create table reviews (id uuid primary key default gen_random_uuid(), place_id uuid references places(id) on delete cascade, user_id uuid references profiles(id), body text, tags text[] default '{}', rating smallint check(rating between 1 and 5), created_at timestamptz default now());
create table place_feature_votes (place_id uuid references places(id) on delete cascade, user_id uuid references profiles(id) on delete cascade, feature text not null check(feature in ('open24','solo','group_friendly','pet','cozy','quiet')), created_at timestamptz default now(), primary key(place_id,user_id,feature));
create table payments (id uuid primary key default gen_random_uuid(), booking_id uuid references bookings(id), user_id uuid references profiles(id), amount integer not null, discount integer default 0, method text check(method in ('card','bank_transfer')), provider text, provider_payment_id text, status text default 'pending' check(status in ('pending','paid','cancelled','refunded')), created_at timestamptz default now());

alter table profiles enable row level security; alter table places enable row level security; alter table visits enable row level security; alter table reports enable row level security; alter table coupons enable row level security; alter table bookings enable row level security;
alter table menus enable row level security; alter table reviews enable row level security; alter table payments enable row level security;
alter table place_feature_votes enable row level security;
create policy "public can read places" on places for select using (true); create policy "public can read active coupons" on coupons for select using (active and expires_on >= current_date);
create policy "users manage own visits" on visits for all using (auth.uid()=user_id) with check(auth.uid()=user_id); create policy "users create reports" on reports for insert with check(auth.uid()=user_id); create policy "users read own reports" on reports for select using(auth.uid()=user_id);
create policy "owners manage own coupons" on coupons for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id); create policy "users create bookings" on bookings for insert with check(auth.uid()=user_id); create policy "users read own bookings" on bookings for select using(auth.uid()=user_id); create policy "owners read place bookings" on bookings for select using(exists(select 1 from places where places.id=bookings.place_id and places.owner_id=auth.uid()));
create policy "public read menus" on menus for select using(active); create policy "owners manage menus" on menus for all using(exists(select 1 from places where places.id=menus.place_id and places.owner_id=auth.uid()));
create policy "public read reviews" on reviews for select using(true); create policy "users create reviews" on reviews for insert with check(auth.uid()=user_id);
create policy "users read own payments" on payments for select using(auth.uid()=user_id);
create policy "public read feature votes" on place_feature_votes for select using(true); create policy "users add feature votes" on place_feature_votes for insert with check(auth.uid()=user_id); create policy "users remove own feature votes" on place_feature_votes for delete using(auth.uid()=user_id);

