const seedPlaces = [
  {id:'p1',name:'모래내 로스터스',type:'cafe',area:'인천 남동구 구월동',lat:37.4492,lng:126.7128,parking:true,publicParking:false,cozy:true,quiet:true,quietTimes:['평일 낮'],desc:'큰 소파와 낮은 조명이 있는 동네 로스터리',reservable:true},
  {id:'p2',name:'개항로 고요',type:'cafe',area:'인천 중구 개항로',lat:37.4739,lng:126.6216,parking:false,publicParking:true,cozy:true,quiet:false,quietTimes:[],desc:'오래된 건물을 살린 작은 방 형태의 카페',reservable:false},
  {id:'p3',name:'송도 테이블',type:'food',area:'인천 연수구 송도동',lat:37.3928,lng:126.6389,parking:true,publicParking:false,cozy:false,quiet:true,quietTimes:['평일 저녁'],desc:'주차가 편하고 좌석 간격이 넓은 다이닝',reservable:true},
  {id:'p4',name:'연남 느린정원',type:'cafe',area:'서울 마포구 연남동',lat:37.5627,lng:126.9257,parking:false,publicParking:true,cozy:true,quiet:true,quietTimes:['평일 낮'],desc:'안쪽 분리 좌석에서 오래 머물기 좋은 공간',reservable:true},
  {id:'p5',name:'성수 담소식당',type:'food',area:'서울 성동구 성수동',lat:37.5446,lng:127.0558,parking:true,publicParking:false,cozy:true,quiet:false,quietTimes:[],desc:'예약 가능한 반분리 룸이 있는 한식당',reservable:true},
  {id:'p6',name:'서촌 구름상점',type:'cafe',area:'서울 종로구 서촌',lat:37.5792,lng:126.9701,parking:false,publicParking:true,cozy:false,quiet:true,quietTimes:['토·일'],desc:'주말 아침이 특히 고요한 작은 찻집',reservable:false},
  {id:'p7',name:'을지로 한상',type:'food',area:'서울 중구 을지로',lat:37.5661,lng:126.9912,parking:false,publicParking:true,cozy:false,quiet:false,quietTimes:[],desc:'계절 메뉴를 내는 캐주얼 한식당',reservable:true},
  {id:'p8',name:'부평 오프화이트',type:'cafe',area:'인천 부평구 부평동',lat:37.4938,lng:126.723,parking:true,publicParking:false,cozy:true,quiet:true,quietTimes:['평일 낮','평일 저녁'],desc:'건물 주차와 푹신한 소파가 있는 대형 카페',reservable:true}
];
const store = {
  get:(key,fallback)=>JSON.parse(localStorage.getItem(`masil_${key}`)||JSON.stringify(fallback)),
  set:(key,value)=>localStorage.setItem(`masil_${key}`,JSON.stringify(value))
};
let places=store.get('places',seedPlaces).map((p,i)=>({...p,hours:p.hours||'매일 10:00 - 22:00',image:p.image||'',phone:p.phone||'',menus:p.menus||[['아메리카노',4500],['시그니처 메뉴',12000]],reviews:p.reviews||['맛있어요','공간이 넓어요',i%2?'혼밥 가능':'모임에 좋아요'],pet:p.pet||i%3===0,solo:p.solo||i%2===0,ownerId:p.ownerId||'demo-owner',acceptingReservations:p.acceptingReservations??p.reservable})), visited=new Set(store.get('visited',[])), coupons=store.get('coupons',[]), bookings=store.get('bookings',[]), activeFilter='all', search='';
const map=L.map('map',{zoomControl:false}).setView([37.52,126.89],10); L.control.zoom({position:'bottomright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map);
let markerLayer=L.layerGroup().addTo(map);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function filtered(){return places.filter(p=>{const match=!search||`${p.name} ${p.area} ${p.desc}`.toLowerCase().includes(search); if(!match)return false; return activeFilter==='all'||(activeFilter==='visited'?visited.has(p.id):p[activeFilter]);});}
function color(p){return visited.has(p.id)?'#40a987':p.type==='cafe'?'#ed744f':'#5387b8'}
function markerIcon(p){return L.divIcon({className:'',html:`<div class="custom-marker" style="background:${color(p)}"><span>${p.type==='cafe'?'☕':'⌂'}</span></div>`,iconSize:[35,35],iconAnchor:[17,34]})}
function tags(p){return [p.parking&&'건물 주차',p.publicParking&&'공용주차장',p.cozy&&'편안해요',p.quiet&&`한적해요${p.quietTimes.length?' · '+p.quietTimes[0]:''}`,visited.has(p.id)&&'탐험 완료'].filter(Boolean)}
function render(){const data=filtered(); markerLayer.clearLayers(); data.forEach(p=>L.marker([p.lat,p.lng],{icon:markerIcon(p)}).addTo(markerLayer).bindTooltip(p.name).on('click',()=>openDetail(p.id)));
  $('#placeList').innerHTML=data.map(p=>`<article class="place-card ${visited.has(p.id)?'visited-card':''}" data-id="${p.id}"><div class="place-thumb">${p.image?`<img src="${p.image}" alt="${p.name}">`:(p.type==='cafe'?'☕':'♨')}</div><div><p>${p.area}</p><h3>${p.name}</h3><p>${p.desc}</p><div class="tags">${tags(p).map(t=>`<span class="tag">${t}</span>`).join('')}</div></div></article>`).join('')||'<p>조건에 맞는 장소가 없어요.</p>';
  $('#resultCount').textContent=`${data.length}곳`; $('#resultTitle').innerHTML=activeFilter==='all'?'오늘 어디로<br>마실 갈까요?':`${$('.filter.active').textContent}<br>장소 모아보기`;
  const count=visited.size; $('#progressText').textContent=`${count}곳 완료`; $('#progressBar').style.width=`${Math.min(100,count/places.length*100)}%`; $$('.place-card').forEach(el=>el.onclick=()=>openDetail(el.dataset.id));
}
function openDetail(id){const p=places.find(x=>x.id===id), pc=coupons.filter(c=>c.placeId===id); map.flyTo([p.lat,p.lng],14); $('#detailContent').innerHTML=`<div class="detail-hero"><button class="close" style="color:white" onclick="detailDialog.close()">×</button><p>${p.area}</p><h2>${p.name}</h2><span>${p.type==='cafe'?'카페':'식당'} · ${p.desc}</span></div><div class="detail-body"><div class="feature-grid"><div class="feature">🚙<br>${p.parking?'건물 내 주차':'주차 없음'}</div><div class="feature">🛋<br>${p.cozy?'편안한 좌석':'일반 좌석'}</div><div class="feature">☁<br>${p.quiet?p.quietTimes.join(' · ')||'한적함':'보통 붐빔'}</div></div>${pc.map(c=>`<div class="coupon"><b>🎟 ${c.title}</b><br><small>${c.condition} · ${c.expires}까지</small></div>`).join('')}<div class="actions"><button class="secondary" onclick="toggleVisited('${p.id}')">${visited.has(p.id)?'✓ 탐험 완료 취소':'✓ 다녀왔어요'}</button>${p.reservable?`<button class="primary" onclick="openBooking('${p.id}')">예약하기</button>`:'<button class="primary" disabled>예약 미지원</button>'}</div></div>`; $('#detailDialog').showModal();}
function toggleVisited(id){visited.has(id)?visited.delete(id):visited.add(id);store.set('visited',[...visited]);$('#detailDialog').close();toast(visited.has(id)?'탐험 완료! 지도에 내 영토가 생겼어요.':'탐험 기록을 취소했어요.');render()}
function openBooking(id){$('#detailDialog').close();$('#bookingForm [name=placeId]').value=id;$('#bookingDialog').showModal()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$$('.filter').forEach(btn=>btn.onclick=()=>{$$('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;render()});
$('#searchInput').oninput=e=>{search=e.target.value.trim().toLowerCase();render();showSearchCreate()}; $('#homeBtn').onclick=()=>{map.setView([37.52,126.89],10);search='';$('#searchInput').value='';render()};
function populatePlaces(){$('#reportPlace').innerHTML=places.map(p=>`<option value="${p.id}">${p.name} · ${p.area}</option>`).join('');$$('.ownerPlace').forEach(s=>s.innerHTML=places.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''))}
$('#openReport').onclick=()=>$('#reportDialog').showModal();$('#openOwner').onclick=()=>{renderBookings();$('#ownerDialog').showModal()}; $$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#reportForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),p=places.find(x=>x.id===$('#reportPlace').value);['parking','cozy','quiet'].forEach(k=>{if(fd.get(k))p[k]=true});if(fd.get('quietTime')&&!p.quietTimes.includes(fd.get('quietTime')))p.quietTimes.push(fd.get('quietTime'));store.set('places',places);e.target.reset();$('#reportDialog').close();render();toast('제보가 지도 필터에 반영됐어요. 고마워요!')};
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab,.tab-pane').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(`[data-pane="${t.dataset.tab}"]`).classList.add('active')});
$('#couponForm').onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));coupons.push({...fd,id:crypto.randomUUID(),claimedBy:[]});store.set('coupons',coupons);e.target.reset();toast('쿠폰이 발행되어 장소 상세에 표시돼요.')};
$('#bookingForm').onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));bookings.push({...fd,id:crypto.randomUUID(),status:'대기'});store.set('bookings',bookings);e.target.reset();$('#bookingDialog').close();toast('예약 요청을 보냈어요. 점주 확인을 기다려주세요.')};
function renderBookings(){$('#bookingList').innerHTML=bookings.length?bookings.map(b=>{const p=places.find(x=>x.id===b.placeId);return `<div class="booking-row"><button onclick="confirmBooking('${b.id}')">${b.status}</button><b>${p?.name}</b><br>${b.name} · ${b.party}명 · ${b.date.replace('T',' ')}</div>`}).join(''):'<p>아직 들어온 예약이 없어요.</p>'}
function confirmBooking(id){const b=bookings.find(x=>x.id===id);b.status=b.status==='대기'?'확정':'대기';store.set('bookings',bookings);renderBookings();toast(`예약을 ${b.status} 상태로 변경했어요.`)}
// --- 확장 서비스 흐름: 인증, 점주 관리, GPS, 쿠폰, 결제 데모 ---
let session=store.get('session',null), accounts=store.get('accounts',[]);
const money=n=>`${Number(n||0).toLocaleString('ko-KR')}원`;
async function hash(text){const bytes=new TextEncoder().encode(text),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function focusForAccount(account){const own=places.find(p=>p.ownerId===account.id);if(account.role==='owner'&&own)return map.setView([own.lat,own.lng],15);const known={'계산역':[37.5433,126.728],'계양도서관':[37.5378,126.7373],'부평역':[37.4895,126.7245],'서울역':[37.5547,126.9707],'송도':[37.3827,126.6564]};const hit=Object.entries(known).find(([k])=>account.homeLocation?.includes(k));if(hit)map.setView(hit[1],15)}
function setSession(account,remember=true){session={id:account.id,name:account.name,email:account.email,role:account.role,homeLocation:account.homeLocation};(remember?localStorage:sessionStorage).setItem('masil_session',JSON.stringify(session));$('#authGate').classList.add('hidden');$('#openOwner').textContent=session.name.slice(0,2);$('#ownerTitle').textContent=session.role==='owner'?'점주 센터':'마이 마실';setTimeout(()=>focusForAccount(session),200);}
function restoreSession(){const saved=localStorage.getItem('masil_session')||sessionStorage.getItem('masil_session');if(saved){session=JSON.parse(saved);$('#authGate').classList.add('hidden');$('#openOwner').textContent=session.name?.slice(0,2)||'MY'}}
$$('.role').forEach(b=>b.onclick=()=>{$$('.role').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm [name=role]').value=b.dataset.role});
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),pw=await hash(f.password),a=accounts.find(x=>x.email===f.email&&x.passwordHash===pw&&x.role===f.role);if(!a)return toast('계정 정보 또는 로그인 유형을 확인해주세요.');setSession(a,!!f.remember);toast(`${a.name}님, 반가워요!`)};
const locationCoords=text=>text.includes('계산')?[37.5433,126.728]:text.includes('계양')?[37.5378,126.7373]:text.includes('부평')?[37.4895,126.7245]:text.includes('송도')?[37.3827,126.6564]:[37.52,126.89];
async function resizeImage(file,maxW=1200,maxH=800){if(!file)return '';const src=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)}),img=await new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=src}),scale=Math.min(1,maxW/img.width,maxH/img.height),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.78)}
$('#signupRole').onchange=e=>{const owner=e.target.value==='owner';$('#ownerSignupFields').hidden=!owner;$('#userSignupFields').hidden=owner;$('#signupForm [name=homeLocation]').required=!owner;['storeName','storeAddress','firstMenu','firstPrice'].forEach(n=>$('#signupForm [name='+n+']').required=owner)};
$('#signupForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd);if(accounts.some(x=>x.email===f.email))return toast('이미 가입된 이메일이에요.');const a={id:crypto.randomUUID(),name:f.name,email:f.email,role:f.role,homeLocation:f.homeLocation||f.storeAddress,passwordHash:await hash(f.password)};accounts.push(a);if(f.role==='owner'){const [lat,lng]=locationCoords(f.storeAddress);places.push({id:crypto.randomUUID(),ownerId:a.id,name:f.storeName,area:f.storeAddress,type:'cafe',lat,lng,image:await resizeImage(fd.get('storeImage')),hours:f.open24?'24시간 운영':'영업시간 등록 필요',menus:[[f.firstMenu,+f.firstPrice,'']],desc:'점주가 등록한 가게',cozy:!!f.cozy,quiet:!!f.quiet,open24:!!f.open24,solo:!!f.solo,groupFriendly:!!f.groupFriendly,parking:false,publicParking:false,pet:false,quietTimes:[],reviews:[],reservable:true});store.set('places',places)}store.set('accounts',accounts);$('#signupDialog').close();populatePlaces();render();setSession(a,true);toast('가입이 완료됐어요.')};
$('#showSignup').onclick=()=>$('#signupDialog').showModal();$('#showRecovery').onclick=()=>$('#recoveryDialog').showModal();$('#demoLogin').onclick=()=>setSession({id:'demo-user',name:'탐험가',email:'demo@masil.local',role:'user'},false);
$('#recoveryForm').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.target).get('email'),a=accounts.find(x=>x.email===email);if(!a)return toast('가입 기록이 없는 이메일이에요.');const temp=Math.random().toString(36).slice(-8);a.passwordHash=await hash(temp);store.set('accounts',accounts);$('#tempPassword').innerHTML=`<div class="temp-pass">임시 비밀번호 <b>${temp}</b><small>로그인 후 새 비밀번호로 변경해주세요.</small></div>`};
function openDetail(id){const p=places.find(x=>x.id===id),pc=coupons.filter(c=>c.placeId===id);map.flyTo([p.lat,p.lng],15);const hero=p.image?`background-image:linear-gradient(0deg,#18251dcc,#18251d11),url('${p.image}')`:'';$('#detailContent').innerHTML=`<div class="detail-hero" style="${hero}"><button class="close" style="color:white" onclick="detailDialog.close()">×</button><p>${p.area}</p><h2>${p.name}</h2><span>${p.type==='cafe'?'카페':'식당'} · ${p.desc}</span></div><div class="detail-body"><div class="detail-meta"><b>⏰ ${p.hours}</b><span>📍 ${p.area}</span></div><div class="feature-grid"><div class="feature">🚙<br>${p.parking?'건물 내 주차':'주차 없음'}</div><div class="feature">🛋<br>${p.cozy?'편안한 좌석':'일반 좌석'}</div><div class="feature">☁<br>${p.quiet?p.quietTimes.join(' · ')||'한적함':'보통 붐빔'}</div></div><h3>메뉴</h3><div class="menu-list">${p.menus.map(m=>`<span>${m[0]}<b>${money(m[1])}</b></span>`).join('')}</div><div class="review-cloud">${[...p.reviews,p.pet&&'반려동물 동반',p.solo&&'혼밥 가능'].filter(Boolean).map(r=>`<i># ${r}</i>`).join('')}</div>${pc.map(c=>`<div class="coupon"><b>🎟 ${c.title} · ${money(c.discount)} 할인</b><br><small>${money(c.minPrice)} 이상 · ${c.expires}까지</small><button onclick="claimCoupon('${c.id}')">쿠폰 받기</button></div>`).join('')}<div class="actions"><button class="secondary" onclick="toggleVisited('${p.id}')">${visited.has(p.id)?'✓ 탐험 완료 취소':'✓ 다녀왔어요'}</button>${p.reservable?`<button class="primary" onclick="openBooking('${p.id}')">예약하기</button>`:'<button class="primary" disabled>예약 미지원</button>'}</div></div>`;$('#detailDialog').showModal()}
function claimCoupon(id){if(!session)return toast('로그인 후 쿠폰을 받을 수 있어요.');const c=coupons.find(x=>x.id===id);c.claimedBy=c.claimedBy||[];if(c.claimedBy.includes(session.id))return toast('이미 받은 쿠폰이에요.');c.claimedBy.push(session.id);store.set('coupons',coupons);toast('쿠폰함에 저장했어요!')}
$('#addMenuRow').onclick=()=>$('#menuEditor').insertAdjacentHTML('beforeend','<div class="menu-edit-row"><button type="button" class="remove-menu">×</button><label>메뉴 이름<input name="menuName" required></label><div class="form-grid"><label>가격<input name="menuPrice" type="number" min="0" required></label><label>메뉴 이미지<input name="menuImageFile" type="file" accept="image/*"></label></div></div>');$('#menuEditor').onclick=e=>{if(e.target.classList.contains('remove-menu'))e.target.closest('.menu-edit-row').remove()};
$('#storeForm').onsubmit=async e=>{e.preventDefault();if(session?.role!=='owner')return toast('점주 계정만 가게 정보를 관리할 수 있어요.');const fd=new FormData(e.target),f=Object.fromEntries(fd),id=f.id||places.find(p=>p.ownerId===session.id)?.id||crypto.randomUUID(),old=places.find(p=>p.id===id),names=fd.getAll('menuName'),prices=fd.getAll('menuPrice'),files=fd.getAll('menuImageFile'),menus=[];for(let i=0;i<names.length;i++)menus.push([names[i],+prices[i],await resizeImage(files[i],500,360)]);const uploaded=await resizeImage(fd.get('imageFile')),p={...old,...f,id,image:uploaded||old?.image||'',lat:+f.lat,lng:+f.lng,ownerId:session.id,reservable:true,quietTimes:old?.quietTimes||['평일 낮'],reviews:old?.reviews||[],menus,parking:!!f.parking,publicParking:!!f.publicParking,cozy:!!f.cozy,quiet:!!f.quiet,open24:!!f.open24,groupFriendly:!!f.groupFriendly,pet:!!f.pet,solo:!!f.solo};places=old?places.map(x=>x.id===id?p:x):[...places,p];store.set('places',places);populatePlaces();render();map.setView([p.lat,p.lng],15);toast('가게 정보가 지도에 반영됐어요.')};
function renderBookings(){$('#bookingList').innerHTML=bookings.length?bookings.map(b=>{const p=places.find(x=>x.id===b.placeId);return `<div class="booking-row"><b>${p?.name}</b><span class="status ${b.status}">${b.status}</span><br>${b.name} · ${b.party}명 · ${b.date.replace('T',' ')}<div class="booking-actions"><button onclick="setBookingStatus('${b.id}','확정')">예약 확인</button><button onclick="setBookingStatus('${b.id}','이용완료')">이용 완료</button><button onclick="setBookingStatus('${b.id}','취소')">취소</button><button onclick="openPayment('${b.id}')">결제</button></div></div>`}).join(''):'<p>아직 들어온 예약이 없어요.</p>'}
function setBookingStatus(id,status){const b=bookings.find(x=>x.id===id);b.status=status;store.set('bookings',bookings);renderBookings();toast(`예약을 ${status} 처리했어요.`)}
function openPayment(id){const b=bookings.find(x=>x.id===id),p=places.find(x=>x.id===b.placeId);$('#paymentForm').dataset.booking=id;$('#paymentSummary').innerHTML=`<div class="payment-total"><span>${p.name} · ${b.party}명</span><b>${money(b.party*10000)}</b></div>`;$('#paymentCoupon').innerHTML='<option value="">쿠폰 사용 안 함</option>'+coupons.filter(c=>c.placeId===p.id&&c.claimedBy?.includes(session?.id)).map(c=>`<option value="${c.id}">${c.title} - ${money(c.discount)}</option>`).join('');$('#paymentDialog').showModal()}
$('#paymentForm').onsubmit=e=>{e.preventDefault();const b=bookings.find(x=>x.id===e.target.dataset.booking);b.payment='테스트 결제완료';b.status='이용완료';store.set('bookings',bookings);$('#paymentDialog').close();renderBookings();toast('테스트 결제가 완료됐어요.')};
$('#locateMe').onclick=()=>{if(!navigator.geolocation)return toast('이 브라우저는 위치 기능을 지원하지 않아요.');navigator.geolocation.getCurrentPosition(pos=>{const {latitude,longitude}=pos.coords;map.setView([latitude,longitude],15);const near=places.filter(p=>map.distance([latitude,longitude],[p.lat,p.lng])<4000);search='';activeFilter='all';render();toast(`현재 위치 주변 ${near.length}곳을 찾았어요.`)},()=>toast('위치 권한을 허용하면 현재 동네부터 보여드려요.'))};
function showSearchCreate(){let old=$('#searchCreate');if(old)old.remove();if(search&&filtered().length===0){const b=document.createElement('button');b.id='searchCreate';b.className='search-create';b.textContent=`＋ “${$('#searchInput').value}” 새 장소 등록`;b.onclick=()=>{$('#newPlaceForm [name=name]').value=$('#searchInput').value;$('#newPlaceDialog').showModal()};$('.side-panel').prepend(b)}}
$('#newPlaceForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd);places.push({id:crypto.randomUUID(),...f,image:await resizeImage(fd.get('imageFile')),lat:+f.lat,lng:+f.lng,type:'cafe',desc:'이용자가 새로 등록한 장소',hours:'정보 확인 중',menus:[['가격 정보 등록 중',0,'']],reviews:['새 장소'],quietTimes:[],reservable:false});store.set('places',places);$('#newPlaceDialog').close();search='';$('#searchInput').value='';populatePlaces();render();toast('새 장소가 지도에 등록됐어요.')};
document.addEventListener('pointermove',e=>{$('#cursorGlow').style.transform=`translate(${e.clientX}px,${e.clientY}px)`});document.addEventListener('pointerdown',e=>{for(let i=0;i<7;i++){const s=document.createElement('i');s.className='click-spark';s.style.cssText=`left:${e.clientX}px;top:${e.clientY}px;--x:${(Math.random()-.5)*80}px;--y:${(Math.random()-.5)*80}px`;document.body.append(s);setTimeout(()=>s.remove(),650)}});for(let i=0;i<18;i++){const p=document.createElement('i');p.style.cssText=`--x:${Math.random()*100}vw;--delay:${Math.random()*8}s;--size:${3+Math.random()*6}px`;$('#particleField').append(p)}
// --- 주소 검색·권한·특징 투표 보강 ---
const featureLabels={open24:'24시간 운영',solo:'혼밥 가능',groupFriendly:'모임 가능',pet:'반려동물 동반 가능',cozy:'편안해요',quiet:'한적해요'};
async function geocodeAddress(query){try{const u=`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=kr&q=${encodeURIComponent(query)}`,r=await fetch(u,{headers:{'Accept-Language':'ko'}}),j=await r.json();if(j[0])return[+j[0].lat,+j[0].lon]}catch(e){}return locationCoords(query)}
function addVote(p,key,userId){p.featureVotes=p.featureVotes||{};p.featureVoters=p.featureVoters||{};p.featureVoters[key]=p.featureVoters[key]||[];if(p.featureVoters[key].includes(userId))return false;p.featureVoters[key].push(userId);p.featureVotes[key]=(p.featureVotes[key]||0)+1;return true}
function sortedFeatures(p){return Object.entries(featureLabels).filter(([k])=>p[k]||p.featureVotes?.[k]).sort((a,b)=>(p.featureVotes?.[b[0]]||0)-(p.featureVotes?.[a[0]]||0))}
function hideCoordinateFields(){['#storeForm','#newPlaceForm'].forEach(sel=>{const lat=$(`${sel} [name=lat]`);if(lat){const box=lat.closest('.form-grid');box.hidden=true;box.querySelectorAll('input').forEach(i=>i.required=false)}})}
hideCoordinateFields();
if(!$('#newPlaceForm [name=open24]'))$('#newPlaceForm .primary').insertAdjacentHTML('beforebegin','<fieldset><legend>직접 확인한 특징</legend><label class="check"><input type="checkbox" name="open24"> 24시간 운영</label><label class="check"><input type="checkbox" name="solo"> 혼밥 가능</label><label class="check"><input type="checkbox" name="groupFriendly"> 모임 가능</label><label class="check"><input type="checkbox" name="pet"> 반려동물 동반 가능</label></fieldset>');
if(!$('#ownerDeleteAccount'))$('#ownerDialog .form-card').insertAdjacentHTML('beforeend','<button id="ownerDeleteAccount" class="danger wide">회원 탈퇴</button>');
$('#quickAdd').onclick=()=>{$('#newPlaceForm [name=name]').value=$('#searchInput').value.trim();$('#newPlaceDialog').showModal()};
function renderSuggestions(){const q=$('#searchInput').value.trim().toLowerCase(),box=$('#searchSuggestions');if(!q){box.innerHTML='';box.classList.remove('show');return}const hits=places.filter(p=>`${p.name} ${p.area}`.toLowerCase().includes(q)).slice(0,6);box.innerHTML=hits.map(p=>`<button data-id="${p.id}"><b>${p.name}</b><small>${p.area}</small></button>`).join('')+`<button class="add-result" data-add="1">＋ “${$('#searchInput').value}” 새 장소 등록</button>`;box.classList.add('show');box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{box.classList.remove('show');openDetail(b.dataset.id)});box.querySelector('[data-add]').onclick=$('#quickAdd').onclick}
$('#searchInput').addEventListener('input',renderSuggestions);document.addEventListener('click',e=>{if(!e.target.closest('.search-box'))$('#searchSuggestions').classList.remove('show')});
const baseSignupSubmit=$('#signupForm').onsubmit;$('#signupForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd);if(accounts.some(x=>x.email===f.email))return toast('이미 가입된 이메일이에요.');const address=f.role==='owner'?f.storeAddress:f.homeLocation,[lat,lng]=await geocodeAddress(address);const a={id:crypto.randomUUID(),name:f.name,email:f.email,role:f.role,homeLocation:address,homeCoords:[lat,lng],passwordHash:await hash(f.password)};accounts.push(a);if(f.role==='owner'){const p={id:crypto.randomUUID(),ownerId:a.id,name:f.storeName,area:f.storeAddress,type:'cafe',lat,lng,image:await resizeImage(fd.get('storeImage')),hours:f.open24?'24시간 운영':'영업시간 등록 필요',menus:[[f.firstMenu,+f.firstPrice,'']],desc:'점주가 등록한 가게',cozy:!!f.cozy,quiet:!!f.quiet,open24:!!f.open24,solo:!!f.solo,groupFriendly:!!f.groupFriendly,parking:false,publicParking:false,pet:false,quietTimes:[],reviews:[],featureVotes:{},featureVoters:{},reservable:true};Object.keys(featureLabels).forEach(k=>{if(p[k])addVote(p,k,a.id)});places.push(p);store.set('places',places)}store.set('accounts',accounts);$('#signupDialog').close();populatePlaces();render();setSession(a,true);map.setView([lat,lng],15);toast('가입이 완료됐어요.')};
const oldSetSession=setSession;setSession=function(account,remember=true){oldSetSession(account,remember);const full=accounts.find(a=>a.id===account.id)||account;if(full.homeCoords)setTimeout(()=>map.setView(full.homeCoords,15),250);const owner=session.role==='owner';$$('#ownerDialog .tab').forEach(t=>t.hidden=!owner);};
$('#openOwner').onclick=()=>{if(!session)return $('#authGate').classList.remove('hidden');if(session.role!=='owner'){$('#accountSummary').innerHTML=`<p><b>${session.name}</b><br>${session.email}<br>기준 위치: ${session.homeLocation||'미등록'}</p>`;return $('#accountDialog').showModal()}const mine=places.find(p=>p.ownerId===session.id);if(mine){const f=$('#storeForm');['id','name','type','area','hours','phone','desc'].forEach(k=>{if(f.elements[k])f.elements[k].value=mine[k]||''});Object.keys(featureLabels).forEach(k=>{if(f.elements[k])f.elements[k].checked=!!mine[k]})}renderBookings();$('#ownerDialog').showModal()};
$('#couponForm').onsubmit=e=>{e.preventDefault();if(session?.role!=='owner')return toast('점주 계정만 쿠폰을 발행할 수 있어요.');const fd=Object.fromEntries(new FormData(e.target)),mine=places.find(p=>p.id===fd.placeId&&p.ownerId===session.id);if(!mine)return toast('본인 가게에만 쿠폰을 발행할 수 있어요.');coupons.push({...fd,id:crypto.randomUUID(),claimedBy:[]});store.set('coupons',coupons);e.target.reset();toast('쿠폰을 발행했어요.')};
const oldRenderBookings=renderBookings;renderBookings=function(){if(session?.role!=='owner')return;const mine=new Set(places.filter(p=>p.ownerId===session.id).map(p=>p.id));const scoped=bookings.filter(b=>mine.has(b.placeId));$('#bookingList').innerHTML=scoped.length?scoped.map(b=>{const p=places.find(x=>x.id===b.placeId);return `<div class="booking-row"><b>${p?.name}</b><span class="status ${b.status}">${b.status}</span><br>${b.name} · ${b.party}명 · ${b.date.replace('T',' ')}<div class="booking-actions"><button onclick="setBookingStatus('${b.id}','확정')">예약 확인</button><button onclick="setBookingStatus('${b.id}','이용완료')">이용 완료</button><button onclick="setBookingStatus('${b.id}','취소')">취소</button></div></div>`}).join(''):'<p>아직 들어온 예약이 없어요.</p>'};
setBookingStatus=function(id,status){if(session?.role!=='owner')return toast('점주만 예약 상태를 변경할 수 있어요.');const b=bookings.find(x=>x.id===id),p=places.find(x=>x.id===b?.placeId);if(!b||p.ownerId!==session.id)return toast('본인 가게 예약만 관리할 수 있어요.');b.status=status;store.set('bookings',bookings);renderBookings();toast(`예약을 ${status} 처리했어요.`)};
const oldStoreSubmit=$('#storeForm').onsubmit;$('#storeForm').onsubmit=async e=>{e.preventDefault();if(session?.role!=='owner')return toast('점주 계정만 가게 정보를 관리할 수 있어요.');const fd=new FormData(e.target),f=Object.fromEntries(fd),id=f.id||places.find(p=>p.ownerId===session.id)?.id||crypto.randomUUID(),old=places.find(p=>p.id===id),[lat,lng]=await geocodeAddress(f.area),names=fd.getAll('menuName'),prices=fd.getAll('menuPrice'),files=fd.getAll('menuImageFile'),menus=[];for(let i=0;i<names.length;i++)menus.push([names[i],+prices[i],await resizeImage(files[i],500,360)||old?.menus?.[i]?.[2]||'']);const uploaded=await resizeImage(fd.get('imageFile')),p={...old,...f,id,image:uploaded||old?.image||'',lat,lng,ownerId:session.id,reservable:true,quietTimes:old?.quietTimes||[],reviews:old?.reviews||[],featureVotes:old?.featureVotes||{},featureVoters:old?.featureVoters||{},menus};Object.keys(featureLabels).forEach(k=>{p[k]=!!f[k];if(p[k])addVote(p,k,session.id)});places=old?places.map(x=>x.id===id?p:x):[...places,p];store.set('places',places);populatePlaces();render();map.setView([lat,lng],15);toast('주소와 가게 정보를 수정했어요.')};
$('#newPlaceForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),[lat,lng]=await geocodeAddress(f.area),p={id:crypto.randomUUID(),...f,image:await resizeImage(fd.get('imageFile')),lat,lng,type:'cafe',desc:'이용자가 새로 등록한 장소',hours:f.open24?'24시간 운영':'정보 확인 중',menus:[['가격 정보 등록 중',0,'']],reviews:[],quietTimes:[],featureVotes:{},featureVoters:{},reservable:false};Object.keys(featureLabels).forEach(k=>{p[k]=!!f[k];if(p[k])addVote(p,k,session?.id||'guest')});places.push(p);store.set('places',places);$('#newPlaceDialog').close();search='';$('#searchInput').value='';populatePlaces();render();map.setView([lat,lng],15);toast('주소를 찾아 새 장소를 등록했어요.')};
function voteFeature(placeId,key){if(!session)return toast('로그인 후 특징을 선택할 수 있어요.');const p=places.find(x=>x.id===placeId);if(!addVote(p,key,session.id))return toast('이미 선택한 특징이에요.');p[key]=true;store.set('places',places);openDetail(placeId);toast('특징 선택이 누적됐어요.')}
const enhancedOpenDetail=openDetail;openDetail=function(id){enhancedOpenDetail(id);const p=places.find(x=>x.id===id),cloud=$('#detailContent .review-cloud');if(cloud){cloud.innerHTML=sortedFeatures(p).map(([k,label])=>`<button onclick="voteFeature('${id}','${k}')"># ${label} <b>${p.featureVotes?.[k]||0}</b></button>`).join('')+cloud.innerHTML}}
$('#logoutBtn').onclick=()=>{localStorage.removeItem('masil_session');sessionStorage.removeItem('masil_session');session=null;$('#accountDialog').close();$('#authGate').classList.remove('hidden')};
$('#deleteAccountBtn').onclick=()=>{if(!session)return;if(!confirm('회원 탈퇴 시 이 브라우저에 저장된 계정 정보가 삭제됩니다. 탈퇴할까요?'))return;accounts=accounts.filter(a=>a.id!==session.id);store.set('accounts',accounts);localStorage.removeItem('masil_session');sessionStorage.removeItem('masil_session');session=null;$('#accountDialog').close();$('#authGate').classList.remove('hidden');toast('회원 탈퇴가 완료됐어요.')};
$('#ownerDeleteAccount').onclick=()=>{if(!session||!confirm('회원 탈퇴 후에도 등록 가게는 검수 대상으로 남습니다. 탈퇴할까요?'))return;accounts=accounts.filter(a=>a.id!==session.id);store.set('accounts',accounts);localStorage.removeItem('masil_session');sessionStorage.removeItem('masil_session');session=null;$('#ownerDialog').close();$('#authGate').classList.remove('hidden');toast('회원 탈퇴가 완료됐어요.')};
window.voteFeature=voteFeature;window.toggleVisited=toggleVisited;window.openBooking=openBooking;window.confirmBooking=confirmBooking;window.setBookingStatus=setBookingStatus;window.openPayment=openPayment;window.claimCoupon=claimCoupon;window.detailDialog=$('#detailDialog');restoreSession();populatePlaces();render();

// --- 2차 보강: 정확한 주소 후보, 이용자 콘텐츠, 점주 운영 상태 ---
$('#storeForm').querySelectorAll('[name=menuName],[name=menuPrice]').forEach(i=>i.required=false);
if(!$('#ownerOperations'))$('#ownerDialog .form-card').insertAdjacentHTML('beforeend','<div id="ownerOperations" class="owner-operations"><button id="toggleReservations" class="secondary">예약 가능/불가</button><button id="deleteStore" class="danger">내 가게 삭제</button><button id="ownerLogout" class="secondary">로그아웃</button></div>');
async function resolveAddress(query){const fallback=locationCoords(query);try{const params=new URLSearchParams({format:'json',limit:'5',countrycodes:'kr',addressdetails:'1',bounded:'1',viewbox:'126.25,37.85,127.25,37.25',q:`${query}, 대한민국`}),r=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{headers:{'Accept-Language':'ko'}}),items=await r.json(),best=items.find(x=>/서울|인천/.test(x.display_name))||items[0];if(best)return{lat:+best.lat,lng:+best.lon,label:best.display_name}}catch(e){}return{lat:fallback[0],lng:fallback[1],label:query}}
sortedFeatures=function(p){return Object.entries(featureLabels).sort((a,b)=>(p.featureVotes?.[b[0]]||0)-(p.featureVotes?.[a[0]]||0))};
const allPlacesFiltered=filtered;filtered=function(){const data=allPlacesFiltered();return session?.role==='owner'?data.filter(p=>p.ownerId===session.id):data};
const roleSetSession=setSession;setSession=function(account,remember=true){roleSetSession(account,remember);const full=accounts.find(a=>a.id===account.id)||account;if(full.homeCoords)map.setView(full.homeCoords,15);if(account.role==='owner'){const mine=places.find(p=>p.ownerId===account.id);if(mine)map.setView([mine.lat,mine.lng],16)}render()};
const currentRestore=restoreSession;restoreSession=function(){currentRestore();if(!session)return;const full=accounts.find(a=>a.id===session.id);if(full?.homeCoords)map.setView(full.homeCoords,15);if(session.role==='owner'){const mine=places.find(p=>p.ownerId===session.id);if(mine)map.setView([mine.lat,mine.lng],16)}render()};
async function resizeMany(list){const out=[];for(const f of [...list].slice(0,6))out.push(await resizeImage(f,1000,750));return out}
$('#newPlaceForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),loc=await resolveAddress(f.area),p={id:crypto.randomUUID(),name:f.name,type:f.type,area:f.area,resolvedAddress:loc.label,image:await resizeImage(fd.get('imageFile')),gallery:await resizeMany(fd.getAll('galleryFiles').filter(x=>x.size)),lat:loc.lat,lng:loc.lng,desc:'이용자가 새로 등록한 장소',hours:f.open24?'24시간 운영':'정보 확인 중',menus:f.menuName?[ [f.menuName,+f.menuPrice||0,''] ]:[],reviews:f.review?[f.review]:[],quietTimes:[],featureVotes:{},featureVoters:{},reservable:false,acceptingReservations:false};Object.keys(featureLabels).forEach(k=>{p[k]=!!f[k];if(p[k])addVote(p,k,session?.id||'guest')});places.push(p);store.set('places',places);e.target.reset();$('#newPlaceDialog').close();search='';$('#searchInput').value='';populatePlaces();render();map.setView([p.lat,p.lng],16);toast(`주소 위치를 “${loc.label.split(',').slice(0,2).join(',')}”로 확인했어요.`)};
$('#storeForm').onsubmit=async e=>{e.preventDefault();if(session?.role!=='owner')return toast('점주 계정만 가게 정보를 관리할 수 있어요.');const submit=e.submitter;submit.disabled=true;submit.textContent='주소 확인·저장 중…';try{const fd=new FormData(e.target),f=Object.fromEntries(fd),id=f.id||places.find(p=>p.ownerId===session.id)?.id||crypto.randomUUID(),old=places.find(p=>p.id===id),loc=await resolveAddress(f.area),names=fd.getAll('menuName'),prices=fd.getAll('menuPrice'),files=fd.getAll('menuImageFile'),menus=[];for(let i=0;i<names.length;i++){if(!names[i])continue;menus.push([names[i],+prices[i]||0,files[i]?.size?await resizeImage(files[i],500,360):old?.menus?.[i]?.[2]||''])}const uploaded=fd.get('imageFile')?.size?await resizeImage(fd.get('imageFile')):'',p={...old,...f,id,image:uploaded||old?.image||'',lat:loc.lat,lng:loc.lng,resolvedAddress:loc.label,ownerId:session.id,reservable:true,acceptingReservations:old?.acceptingReservations??true,quietTimes:old?.quietTimes||[],reviews:old?.reviews||[],featureVotes:old?.featureVotes||{},featureVoters:old?.featureVoters||{},menus:menus.length?menus:(old?.menus||[])};Object.keys(featureLabels).forEach(k=>{p[k]=!!f[k];if(p[k])addVote(p,k,session.id)});places=old?places.map(x=>x.id===id?p:x):[...places,p];store.set('places',places);populatePlaces();render();map.setView([p.lat,p.lng],16);toast('가게 정보가 저장됐어요.')}catch(err){toast('저장 중 오류가 발생했어요. 이미지 크기와 주소를 확인해주세요.')}finally{submit.disabled=false;submit.textContent='가게 정보 저장'}};
renderBookings=function(){if(session?.role!=='owner')return;const mine=new Set(places.filter(p=>p.ownerId===session.id).map(p=>p.id)),scoped=bookings.filter(b=>mine.has(b.placeId));$('#bookingList').innerHTML=scoped.length?scoped.map(b=>{const p=places.find(x=>x.id===b.placeId);return `<div class="booking-row"><b>${p?.name}</b><span class="status ${b.status}">${b.status}</span><br><b>${b.name}</b> · ${b.party}명<br>📞 ${b.phone||'미입력'} · 🕒 ${b.date.replace('T',' ')}<div class="booking-actions"><button onclick="setBookingStatus('${b.id}','확정')">예약 확인</button><button onclick="setBookingStatus('${b.id}','이용완료')">이용 완료</button><button onclick="setBookingStatus('${b.id}','취소')">취소</button></div></div>`}).join(''):'<p>아직 들어온 예약이 없어요.</p>'};
const detailWithVotes=openDetail;openDetail=function(id){detailWithVotes(id);const p=places.find(x=>x.id===id),body=$('#detailContent .detail-body'),reserve=body.querySelector('.actions .primary'),menu=body.querySelector('.menu-list');if(menu)menu.innerHTML=p.menus.length?p.menus.map(m=>`<span>${m[2]?`<img src="${m[2]}" alt="${m[0]}">`:''}<em>${m[0]}</em><b>${money(m[1])}</b></span>`).join(''):'<small>등록된 메뉴가 아직 없어요.</small>';if(reserve){reserve.disabled=!p.acceptingReservations;reserve.textContent=p.acceptingReservations?'예약하기':'현재 예약 불가'}if(p.gallery?.length)body.insertAdjacentHTML('afterbegin',`<div class="gallery-strip">${p.gallery.map(x=>`<img src="${x}" alt="${p.name} 추가 사진">`).join('')}</div>`);body.insertAdjacentHTML('beforeend',`<form class="review-form" onsubmit="addReview(event,'${id}')"><label>사진 추가<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><label>리뷰 쓰기<textarea name="review" required></textarea></label><button class="secondary">리뷰 등록</button></form>`)};
async function addReview(e,id){e.preventDefault();if(!session)return toast('로그인 후 리뷰를 등록할 수 있어요.');const fd=new FormData(e.target),p=places.find(x=>x.id===id),photo=fd.get('photo')?.size?await resizeImage(fd.get('photo'),1000,750):'';p.reviews.push(fd.get('review'));if(photo){p.gallery=p.gallery||[];p.gallery.push(photo)}store.set('places',places);openDetail(id);toast('사진과 리뷰가 등록됐어요.')}
$('#toggleReservations').onclick=()=>{const p=places.find(x=>x.ownerId===session?.id);if(!p)return toast('먼저 가게를 등록해주세요.');p.acceptingReservations=!p.acceptingReservations;store.set('places',places);$('#toggleReservations').textContent=p.acceptingReservations?'예약 가능 상태':'예약 불가 상태';toast(p.acceptingReservations?'예약을 받기 시작했어요.':'예약 접수를 중단했어요.')};
$('#deleteStore').onclick=()=>{const p=places.find(x=>x.ownerId===session?.id);if(!p)return toast('삭제할 가게가 없어요.');if(!confirm(`“${p.name}”을 지도에서 삭제할까요?`))return;places=places.filter(x=>x.id!==p.id);store.set('places',places);populatePlaces();render();$('#ownerDialog').close();toast('본인 가게를 삭제했어요.')};
$('#ownerLogout').onclick=()=>{localStorage.removeItem('masil_session');sessionStorage.removeItem('masil_session');session=null;$('#ownerDialog').close();$('#authGate').classList.remove('hidden');render()};
window.addReview=addReview;window.voteFeature=voteFeature;window.openDetail=openDetail;window.setBookingStatus=setBookingStatus;restoreSession();render();

// --- 3차 보강: 선택 취소, 위치 핀 보정, 메뉴판·홍보 사진, 내 예약 ---
featureLabels.splitRoom='분리된 룸';
if($('#newPlaceForm fieldset')&&!$('#newPlaceForm [name=splitRoom]'))$('#newPlaceForm fieldset').insertAdjacentHTML('beforeend','<label class="check"><input type="checkbox" name="splitRoom"> 분리된 룸</label>');
if(!$('#storeForm [name=menuBoardFile]'))$('#menuEditor').insertAdjacentHTML('beforebegin','<label>대표 메뉴판 이미지<input name="menuBoardFile" type="file" accept="image/jpeg,image/png,image/webp"></label><label>홍보 사진 여러 장<input name="galleryFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div class="form-grid"><label>영업 상태<select name="businessStatus"><option value="영업 중">영업 중</option><option value="영업 중단">영업 중단</option><option value="휴가">휴가</option><option value="영업 종료">영업 종료</option><option value="오픈 준비">오픈 준비</option></select></label><label>주소 위치 확인<button type="button" id="verifyStoreLocation" class="secondary">지도에서 확인·수정</button></label></div><p id="locationHelp" class="form-note"></p>');
if(!$('#storeForm [name=splitRoom]'))$('#storeForm fieldset').insertAdjacentHTML('beforeend','<label class="check"><input type="checkbox" name="splitRoom"> 분리된 룸</label>');
let correctionMarker=null;
$('#verifyStoreLocation').onclick=async()=>{const area=$('#storeForm [name=area]').value.trim();if(!area)return toast('먼저 주소를 입력해주세요.');const loc=await resolveAddress(area);map.setView([loc.lat,loc.lng],17);if(correctionMarker)correctionMarker.remove();correctionMarker=L.marker([loc.lat,loc.lng],{draggable:true}).addTo(map);$('#storeForm').dataset.pickedLat=loc.lat;$('#storeForm').dataset.pickedLng=loc.lng;$('#locationHelp').textContent=`검색 위치: ${loc.label} · 틀리면 지도 마커를 정확한 건물로 드래그하세요.`;correctionMarker.on('dragend',()=>{const v=correctionMarker.getLatLng();$('#storeForm').dataset.pickedLat=v.lat;$('#storeForm').dataset.pickedLng=v.lng;$('#locationHelp').textContent='사용자가 지도에서 직접 보정한 위치로 저장됩니다.'});$('#ownerDialog').close();toast('지도 마커를 확인하고, 수정 후 점주센터를 다시 열어 저장하세요.')};
function toggleFeatureVote(p,key,userId){p.featureVotes=p.featureVotes||{};p.featureVoters=p.featureVoters||{};p.featureVoters[key]=p.featureVoters[key]||[];const i=p.featureVoters[key].indexOf(userId);if(i>=0){p.featureVoters[key].splice(i,1);p.featureVotes[key]=Math.max(0,(p.featureVotes[key]||1)-1);p[key]=p.featureVotes[key]>0;return false}p.featureVoters[key].push(userId);p.featureVotes[key]=(p.featureVotes[key]||0)+1;p[key]=true;return true}
voteFeature=function(placeId,key){if(!session)return toast('로그인 후 특징을 선택할 수 있어요.');const p=places.find(x=>x.id===placeId),selected=toggleFeatureVote(p,key,session.id);store.set('places',places);openDetail(placeId);toast(selected?'특징을 선택했어요.':'특징 선택을 취소했어요.')};
claimCoupon=function(id){if(!session)return toast('로그인 후 쿠폰을 받을 수 있어요.');const c=coupons.find(x=>x.id===id);c.claimedBy=c.claimedBy||[];if(c.claimedBy.includes(session.id))return toast('이미 받은 쿠폰이에요.');c.claimedBy.push(session.id);store.set('coupons',coupons);toast('쿠폰이 발급됐어요!')};
const ownerStoreSubmit=$('#storeForm').onsubmit;$('#storeForm').onsubmit=async e=>{e.preventDefault();if(session?.role!=='owner')return toast('점주 계정만 수정할 수 있어요.');const submit=e.submitter;submit.disabled=true;submit.textContent='저장 중…';try{const fd=new FormData(e.target),f=Object.fromEntries(fd),old=places.find(p=>p.ownerId===session.id),loc=e.target.dataset.pickedLat?{lat:+e.target.dataset.pickedLat,lng:+e.target.dataset.pickedLng,label:'지도에서 직접 보정'}:await resolveAddress(f.area),names=fd.getAll('menuName'),prices=fd.getAll('menuPrice'),files=fd.getAll('menuImageFile'),menus=[];for(let i=0;i<names.length;i++){if(!names[i])continue;menus.push([names[i],+prices[i]||0,files[i]?.size?await resizeImage(files[i],500,360):old?.menus?.[i]?.[2]||''])}const p={...old,...f,id:old?.id||crypto.randomUUID(),ownerId:session.id,lat:loc.lat,lng:loc.lng,image:fd.get('imageFile')?.size?await resizeImage(fd.get('imageFile')):old?.image||'',menuBoard:fd.get('menuBoardFile')?.size?await resizeImage(fd.get('menuBoardFile'),1200,1600):old?.menuBoard||'',gallery:[...(old?.gallery||[]),...await resizeMany(fd.getAll('galleryFiles').filter(x=>x.size))],menus:menus.length?menus:(old?.menus||[]),reviews:old?.reviews||[],featureVotes:old?.featureVotes||{},featureVoters:old?.featureVoters||{},acceptingReservations:old?.acceptingReservations??true,reservable:true,quietTimes:old?.quietTimes||[]};Object.keys(featureLabels).forEach(k=>{if(f[k]&&!p.featureVoters[k]?.includes(session.id))toggleFeatureVote(p,k,session.id)});places=old?places.map(x=>x.id===old.id?p:x):[...places,p];store.set('places',places);populatePlaces();render();map.setView([p.lat,p.lng],17);toast('가게 정보와 이미지가 저장됐어요.')}catch(err){toast('저장하지 못했어요. 이미지 용량이나 입력값을 확인해주세요.')}finally{submit.disabled=false;submit.textContent='가게 정보 저장'}};
$('#openOwner').onclick=()=>{if(!session)return $('#authGate').classList.remove('hidden');if(session.role!=='owner'){renderUserAccount();return $('#accountDialog').showModal()}const mine=places.find(p=>p.ownerId===session.id),f=$('#storeForm');if(mine){['id','name','type','area','hours','phone','desc','businessStatus'].forEach(k=>{if(f.elements[k])f.elements[k].value=mine[k]||''});Object.keys(featureLabels).forEach(k=>{if(f.elements[k])f.elements[k].checked=mine.featureVoters?.[k]?.includes(session.id)||false});$('#menuEditor').innerHTML=mine.menus.length?mine.menus.map((m,i)=>`<div class="menu-edit-row"><button type="button" class="remove-menu">×</button><label>메뉴 이름<input name="menuName" value="${m[0]}" placeholder="메뉴 이름"></label><div class="form-grid"><label>가격<input name="menuPrice" type="number" min="0" value="${m[1]}"></label><label>메뉴 이미지<input name="menuImageFile" type="file" accept="image/*">${m[2]?'<small>기존 이미지 등록됨</small>':''}</label></div></div>`).join(''):$('#menuEditor').innerHTML;map.setView([mine.lat,mine.lng],16);$('#toggleReservations').textContent=mine.acceptingReservations?'예약 가능 상태':'예약 불가 상태'}renderBookings();render();$('#ownerDialog').showModal()};
$('#bookingForm').onsubmit=e=>{e.preventDefault();if(!session)return toast('로그인 후 예약할 수 있어요.');const fd=Object.fromEntries(new FormData(e.target)),p=places.find(x=>x.id===fd.placeId);if(!p?.acceptingReservations)return toast('현재 예약을 받지 않는 가게예요.');bookings.push({...fd,id:crypto.randomUUID(),userId:session.id,status:'대기'});store.set('bookings',bookings);e.target.reset();$('#bookingDialog').close();toast('예약 요청을 보냈어요.')};
setBookingStatus=function(id,status){if(session?.role!=='owner')return toast('점주만 예약 상태를 변경할 수 있어요.');const b=bookings.find(x=>x.id===id),p=places.find(x=>x.id===b?.placeId);if(!b||p.ownerId!==session.id)return toast('본인 가게 예약만 관리할 수 있어요.');b.status=status;if(status==='이용완료'){visited.add(b.placeId);store.set('visited',[...visited])}store.set('bookings',bookings);renderBookings();render();toast(`예약을 ${status} 처리했어요.`)};
function renderUserAccount(){const mine=bookings.filter(b=>b.userId===session.id);$('#accountSummary').innerHTML=`<p><b>${session.name}</b><br>${session.email}</p><form id="homeUpdateForm"><label>내 기준 주소<input name="homeLocation" value="${session.homeLocation||''}" required></label><button class="secondary">주소 저장</button></form><h3>내 예약</h3><div class="my-bookings">${mine.length?mine.map(b=>{const p=places.find(x=>x.id===b.placeId);return `<p><b>${p?.name}</b><span>${b.status}</span><br>${b.date.replace('T',' ')} · ${b.party}명 · ${b.phone||''}</p>`}).join(''):'<small>예약 내역이 없어요.</small>'}</div>`;$('#homeUpdateForm').onsubmit=async e=>{e.preventDefault();const q=new FormData(e.target).get('homeLocation'),loc=await resolveAddress(q),a=accounts.find(x=>x.id===session.id);session.homeLocation=q;session.homeCoords=[loc.lat,loc.lng];if(a){a.homeLocation=q;a.homeCoords=session.homeCoords;store.set('accounts',accounts)}localStorage.setItem('masil_session',JSON.stringify(session));map.setView(session.homeCoords,15);toast('내 기준 주소를 저장했어요.')}}
const mediaDetail=openDetail;openDetail=function(id){mediaDetail(id);const p=places.find(x=>x.id===id),body=$('#detailContent .detail-body'),features=body.querySelector('.feature-grid'),cloud=body.querySelector('.review-cloud'),gallery=body.querySelector('.gallery-strip');body.querySelectorAll('.feature').forEach(x=>{if(x.textContent.includes('편안한 좌석'))x.innerHTML='🛋<br>편안한 쇼파'});if(gallery&&features)features.insertAdjacentElement('afterend',gallery);if(p.menuBoard){const el=document.createElement('div');el.className='menu-board';el.innerHTML=`<h3>대표 메뉴판</h3><img src="${p.menuBoard}" alt="${p.name} 메뉴판">`;gallery?gallery.insertAdjacentElement('afterend',el):features.insertAdjacentElement('afterend',el)}if(cloud)cloud.innerHTML=sortedFeatures(p).map(([k,label])=>{const on=p.featureVoters?.[k]?.includes(session?.id);return `<button class="${on?'selected':''}" onclick="voteFeature('${id}','${k}')"># ${label} <b>${p.featureVotes?.[k]||0}</b></button>`}).join('');const oldReviews=body.querySelector('.reviews-section');if(oldReviews)oldReviews.remove();body.querySelector('.review-form')?.insertAdjacentHTML('beforebegin',`<section class="reviews-section"><h3>방문자 리뷰</h3>${p.reviews.length?p.reviews.map(r=>`<p>${r}</p>`).join(''):'<small>아직 작성된 리뷰가 없어요.</small>'}</section>`);const hero=$('#detailContent .detail-hero');hero.insertAdjacentHTML('beforeend',`<b class="business-badge">${p.businessStatus||'영업 중'}</b>`)};
window.voteFeature=voteFeature;window.claimCoupon=claimCoupon;window.addReview=addReview;window.openDetail=openDetail;window.setBookingStatus=setBookingStatus;render();

// --- 4차 보강: 미디어 분리, 즉시 위치 반영, 점주 대시보드, 길찾기 ---
Object.assign(featureLabels,{dateSpot:'데이트 장소 추천',parking:'건물 내 주차',publicParking:'공용주차장',cozy:'편안해요',quiet:'한적해요'});
const unifiedFeatures=[['parking','건물 내 주차 가능'],['publicParking','공용주차장 인접'],['cozy','소파·분리 공간이 있어 편안함'],['quiet','사람이 적어 한적함'],['splitRoom','분리된 룸'],['solo','혼밥 가능해요'],['groupFriendly','모임 가능해요'],['pet','반려동물 동반 가능해요'],['dateSpot','데이트 장소 추천'],['open24','24시간 운영']];
function addFeatureInputs(form){let fs=form.querySelector('fieldset');if(!fs){fs=document.createElement('fieldset');fs.innerHTML='<legend>직접 확인한 특징</legend>';form.querySelector('.primary').before(fs)}for(const [k,label] of unifiedFeatures)if(!fs.querySelector(`[name="${k}"]`))fs.insertAdjacentHTML('beforeend',`<label class="check"><input type="checkbox" name="${k}"> ${label}</label>`)}
addFeatureInputs($('#newPlaceForm'));addFeatureInputs($('#reportForm'));
const firstNewMenu=$('#newPlaceForm [name=menuName]').closest('.form-grid');firstNewMenu.id='newMenuEditor';firstNewMenu.querySelector('[name=menuPrice]').type='text';firstNewMenu.querySelector('[name=menuPrice]').removeAttribute('min');if(!$('#addNewMenu'))firstNewMenu.insertAdjacentHTML('afterend','<button type="button" id="addNewMenu" class="secondary">＋ 메뉴 추가</button>');
$('#addNewMenu').onclick=()=>$('#newMenuEditor').insertAdjacentHTML('beforeend','<label>메뉴 이름<input name="menuName" placeholder="메뉴 이름"></label><label>가격<input name="menuPrice" type="text" placeholder="변동 가능"></label>');
$('#storeForm').querySelectorAll('[name=menuPrice]').forEach(i=>{i.type='text';i.removeAttribute('min')});
if(!$('#storeForm [name=closedDate]'))$('#storeForm [name=businessStatus]').closest('.form-grid').insertAdjacentHTML('afterend','<label>휴가·영업중단·공사·폐업일 안내<input name="closedDate" placeholder="예: 8월 20일까지 휴가 / 2026-09-01 폐업"></label>');
$('#storeForm [name=businessStatus]').insertAdjacentHTML('beforeend','<option value="공사 중">공사 중</option><option value="폐업">폐업</option>');
if(!$('#mapCorrection'))document.body.insertAdjacentHTML('beforeend','<div id="mapCorrection"><b>가게 위치를 정확한 건물로 옮기세요</b><button id="applyMapPosition">이 위치로 수정 반영</button><button id="cancelMapPosition">취소</button></div>');
$('#verifyStoreLocation').onclick=async()=>{const p=places.find(x=>x.ownerId===session?.id),area=$('#storeForm [name=area]').value.trim();if(!area)return toast('먼저 주소를 입력해주세요.');const loc=await resolveAddress(area);$('#ownerDialog').close();map.setView([p?.lat||loc.lat,p?.lng||loc.lng],18);if(correctionMarker)correctionMarker.remove();correctionMarker=L.marker([p?.lat||loc.lat,p?.lng||loc.lng],{draggable:true}).addTo(map);$('#mapCorrection').classList.add('show')};
$('#applyMapPosition').onclick=()=>{const p=places.find(x=>x.ownerId===session?.id);if(!p||!correctionMarker)return;const v=correctionMarker.getLatLng();p.lat=v.lat;p.lng=v.lng;store.set('places',places);$('#storeForm').dataset.pickedLat=v.lat;$('#storeForm').dataset.pickedLng=v.lng;$('#mapCorrection').classList.remove('show');correctionMarker.remove();correctionMarker=null;render();map.setView([p.lat,p.lng],18);toast('끌어놓은 위치로 즉시 수정 반영했어요.')};
$('#cancelMapPosition').onclick=()=>{$('#mapCorrection').classList.remove('show');if(correctionMarker)correctionMarker.remove();correctionMarker=null};
const previousStoreSave=$('#storeForm').onsubmit;$('#storeForm').onsubmit=async e=>{e.preventDefault();if(session?.role!=='owner')return toast('점주만 수정할 수 있어요.');const submit=e.submitter;submit.disabled=true;try{const fd=new FormData(e.target),f=Object.fromEntries(fd),old=places.find(p=>p.ownerId===session.id),loc=e.target.dataset.pickedLat?{lat:+e.target.dataset.pickedLat,lng:+e.target.dataset.pickedLng}:await resolveAddress(f.area),names=fd.getAll('menuName'),prices=fd.getAll('menuPrice'),files=fd.getAll('menuImageFile'),stocks=fd.getAll('menuLowStock'),menus=[];for(let i=0;i<names.length;i++)if(names[i])menus.push([names[i],prices[i]||'가격 문의',files[i]?.size?await resizeImage(files[i],500,360):old?.menus?.[i]?.[2]||'',!!stocks[i]]);const added=await resizeMany(fd.getAll('galleryFiles').filter(x=>x.size)),p={...old,...f,id:old?.id||crypto.randomUUID(),ownerId:session.id,lat:loc.lat,lng:loc.lng,image:fd.get('imageFile')?.size?await resizeImage(fd.get('imageFile')):old?.image||'',menuBoard:fd.get('menuBoardFile')?.size?await resizeImage(fd.get('menuBoardFile'),1200,1600):old?.menuBoard||'',ownerGallery:[...(old?.ownerGallery||old?.gallery||[]),...added],visitorGallery:old?.visitorGallery||[],menus:menus.length?menus:(old?.menus||[]),reviews:old?.reviews||[],featureVotes:old?.featureVotes||{},featureVoters:old?.featureVoters||{},acceptingReservations:old?.acceptingReservations??true,reservable:true,quietTimes:old?.quietTimes||[]};places=old?places.map(x=>x.id===old.id?p:x):[...places,p];store.set('places',places);delete e.target.dataset.pickedLat;delete e.target.dataset.pickedLng;populatePlaces();render();toast('가게 정보가 저장됐어요.')}catch(err){toast('저장에 실패했어요. 필수 입력값을 확인해주세요.')}finally{submit.disabled=false}};
function renderOwnerMediaManager(p){let box=$('#ownerMediaManager');if(!box){$('#storeForm [name=galleryFiles]').closest('label').insertAdjacentHTML('afterend','<div id="ownerMediaManager" class="media-manager"></div>');box=$('#ownerMediaManager')}box.innerHTML=(p.ownerGallery||p.gallery||[]).map((x,i)=>`<span><img src="${x}" alt="홍보 사진 ${i+1}"><button type="button" onclick="deleteOwnerPhoto(${i})">× 삭제</button></span>`).join('')}
function deleteOwnerPhoto(i){const p=places.find(x=>x.ownerId===session?.id);p.ownerGallery=p.ownerGallery||p.gallery||[];p.ownerGallery.splice(i,1);store.set('places',places);renderOwnerMediaManager(p);toast('선택한 홍보 사진을 삭제했어요.')}
const ownerOpenV4=$('#openOwner').onclick;$('#openOwner').onclick=()=>{ownerOpenV4();if(session?.role==='owner'){const p=places.find(x=>x.ownerId===session.id);$('#openOwner').textContent='가게 정보수정';if(p){renderOwnerMediaManager(p);const f=$('#storeForm');f.elements.closedDate.value=p.closedDate||'';const rows=$$('#menuEditor .menu-edit-row');rows.forEach((row,i)=>{if(!row.querySelector('[name=menuLowStock]'))row.insertAdjacentHTML('beforeend',`<label class="check"><input type="checkbox" name="menuLowStock" value="${i}" ${p.menus[i]?.[3]?'checked':''}> 남은 수량 얼마 안 남음</label>`)});}}};
const bookingStatusV4=setBookingStatus;setBookingStatus=function(id,status){bookingStatusV4(id,status);render()};
const reportSubmitV4=$('#reportForm').onsubmit;$('#reportForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),p=places.find(x=>x.id===$('#reportPlace').value);for(const [k] of unifiedFeatures)if(fd.get(k)){if(!p.featureVoters?.[k]?.includes(session?.id||'reporter'))toggleFeatureVote(p,k,session?.id||'reporter')}if(fd.get('quietTime')&&!p.quietTimes.includes(fd.get('quietTime')))p.quietTimes.push(fd.get('quietTime'));store.set('places',places);e.target.reset();$('#reportDialog').close();render();toast('제보한 특징이 지도 필터에 반영됐어요.')};
addReview=async function(e,id){e.preventDefault();if(!session)return toast('로그인 후 리뷰를 등록할 수 있어요.');const fd=new FormData(e.target),p=places.find(x=>x.id===id),photo=fd.get('photo')?.size?await resizeImage(fd.get('photo'),1000,750):'';p.reviews.push(fd.get('review'));if(photo){p.visitorGallery=p.visitorGallery||[];p.visitorGallery.push(photo)}store.set('places',places);openDetail(id);toast('방문자 리뷰를 등록했어요.')};
function routeEstimate(mode,distance){const cfg={transit:[22,1550,'대중교통'],walk:[4.5,0,'도보'],drive:[28,Math.max(0,Math.round(distance*110)),'자동차'],bike:[13,0,'자전거']}[mode],minutes=Math.max(1,Math.round(distance/cfg[0]*60));return{minutes,cost:cfg[1],label:cfg[2]}}
function openRoute(id){const p=places.find(x=>x.id===id);if(!$('#routeDialog'))document.body.insertAdjacentHTML('beforeend','<dialog id="routeDialog"><div class="form-card"><button class="close" onclick="routeDialog.close()">×</button><p class="eyebrow">ROUTE GUIDE</p><h2>길찾기</h2><p id="routeTarget"></p><div class="route-modes"><button data-mode="transit">🚌 대중교통</button><button data-mode="walk">🚶 도보</button><button data-mode="drive">🚗 자동차</button><button data-mode="bike">🚲 자전거</button></div><div id="routeResult"></div><a id="naverRoute" class="primary route-link" target="_blank">네이버 지도에서 자세히 보기</a></div></dialog>');$('#routeTarget').textContent=`도착: ${p.name} · ${p.area}`;const start=map.getCenter(),km=map.distance(start,[p.lat,p.lng])/1000;$$('#routeDialog [data-mode]').forEach(b=>b.onclick=()=>{const v=routeEstimate(b.dataset.mode,km);$('#routeResult').innerHTML=`<b>${v.label}</b><strong>약 ${v.minutes}분</strong><span>${km.toFixed(1)}km · 예상 비용 ${money(v.cost)}</span><small>실시간 교통·노선이 아닌 참고용 예상치입니다.</small>`});$('#routeDialog [data-mode=transit]').click();$('#naverRoute').href=`https://map.naver.com/p/search/${encodeURIComponent(p.name+' '+p.area)}`;$('#routeDialog').showModal()}
const detailV4=openDetail;openDetail=function(id){detailV4(id);const p=places.find(x=>x.id===id),body=$('#detailContent .detail-body'),features=body.querySelector('.feature-grid');body.querySelectorAll('.gallery-strip,.menu-board,.visitor-photos,.reviews-section').forEach(x=>x.remove());const ownerMedia=[p.menuBoard,...(p.ownerGallery||p.gallery||[])].filter(Boolean);if(ownerMedia.length)features.insertAdjacentHTML('afterend',`<section class="owner-media"><h3>메뉴판·가게 사진</h3><div class="media-slider">${ownerMedia.map((x,i)=>`<img src="${x}" alt="${i?'가게 홍보 사진':'대표 메뉴판'}">`).join('')}</div></section>`);const reviewForm=body.querySelector('.review-form');if(p.visitorGallery?.length)reviewForm.insertAdjacentHTML('beforebegin',`<section class="visitor-photos"><h3>방문자 사진</h3><div class="media-slider">${p.visitorGallery.map(x=>`<img src="${x}" alt="방문자 사진">`).join('')}</div></section>`);reviewForm.insertAdjacentHTML('beforebegin',`<section class="reviews-section"><h3>방문자 리뷰</h3>${p.reviews.length?p.reviews.map(r=>`<p>${r}</p>`).join(''):'<small>아직 리뷰가 없어요.</small>'}</section>`);body.querySelector('.actions').insertAdjacentHTML('beforebegin',`<div class="route-actions"><button onclick="toast('현재 지도 중심을 출발지로 설정했어요.')">출발</button><button onclick="openRoute('${id}')">도착·길찾기</button></div>`);const status=$('#detailContent .business-badge');if(status)status.textContent=`${p.businessStatus||'영업 중'}${p.closedDate?' · '+p.closedDate:''}`};
const baseRenderV4=render;render=function(){baseRenderV4();const owner=session?.role==='owner',heading=$('.panel-heading'),progress=$('.progress-card');heading.style.display=owner?'none':'';progress.style.display=owner?'none':'';if(!owner)return;const p=places.find(x=>x.ownerId===session.id),mine=p?bookings.filter(b=>b.placeId===p.id):[];$('#placeList').innerHTML=p?`<article class="owner-store-card" onclick="openDetail('${p.id}')">${p.image?`<img src="${p.image}" alt="${p.name}">`:''}<p class="eyebrow">내 가게 정보</p><h2>${p.name}</h2><p>${p.area}<br>${p.hours}</p><b>${p.businessStatus||'영업 중'} ${p.closedDate||''}</b></article><h3>들어온 예약 ${mine.length}건</h3>${mine.map(b=>`<div class="booking-row"><b>${b.name}</b> · ${b.party}명<br>📞 ${b.phone||''} · 🕒 ${b.date.replace('T',' ')}<div class="booking-actions"><button onclick="setBookingStatus('${b.id}','확정')">예약 확인</button><button onclick="setBookingStatus('${b.id}','취소')">예약 취소</button><button onclick="setBookingStatus('${b.id}','이용완료')">이용 완료</button></div></div>`).join('')}`:'<button class="primary" onclick="openOwner.click()">내 가게를 등록해주세요</button>'};
$('#addMenuRow').onclick=()=>$('#menuEditor').insertAdjacentHTML('beforeend','<div class="menu-edit-row"><button type="button" class="remove-menu">×</button><label>메뉴 이름<input name="menuName" placeholder="메뉴 이름"></label><div class="form-grid"><label>가격<input name="menuPrice" type="text" placeholder="변동 가능"></label><label>메뉴 이미지<input name="menuImageFile" type="file" accept="image/*"></label></div><label class="check"><input type="checkbox" name="menuLowStock"> 남은 수량 얼마 안 남음</label></div>');
const priceDetailV4=openDetail;openDetail=function(id){priceDetailV4(id);const p=places.find(x=>x.id===id);$$('#detailContent .menu-list span').forEach((row,i)=>{const value=p.menus[i]?.[1],b=row.querySelector('b');if(b)b.textContent=typeof value==='number'?money(value):(value||'가격 문의');if(p.menus[i]?.[3])row.insertAdjacentHTML('beforeend','<i class="low-stock">수량 얼마 안 남음</i>')})};
$('#openOwner').addEventListener('click',()=>setTimeout(()=>$$('#menuEditor [name=menuPrice]').forEach(i=>{i.type='text';i.removeAttribute('min')}),0));
window.deleteOwnerPhoto=deleteOwnerPhoto;window.addReview=addReview;window.openRoute=openRoute;window.openDetail=openDetail;window.setBookingStatus=setBookingStatus;render();

// --- 5차 보강: 수도권 주소 안전장치, 이용자 핀 보정·삭제, OSM 장소 불러오기 ---
resolveAddress=async function(query){
  const raw=String(query||'').trim(),cleaned=raw.replace(/\s+(지하\s*)?\d+층.*$/,'').trim();
  const allowed=(lat,lng)=>lat>=37.20&&lat<=37.90&&lng>=126.20&&lng<=127.30;
  try{const params=new URLSearchParams({format:'json',limit:'10',countrycodes:'kr',addressdetails:'1',bounded:'1',viewbox:'126.20,37.90,127.30,37.20',q:`${cleaned}, 대한민국`}),response=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{headers:{'Accept-Language':'ko'}}),items=await response.json(),best=items.find(x=>allowed(+x.lat,+x.lon)&&/인천|서울/.test(x.display_name||''));if(best)return{lat:+best.lat,lng:+best.lon,label:best.display_name,verified:true}}catch(error){}
  if(/황어로|계양초|장기동/.test(cleaned))return{lat:37.5785,lng:126.7315,label:'인천 계양구 황어로 인근 (핀으로 정확한 건물을 선택하세요)',verified:false};
  if(/계양구/.test(cleaned))return{lat:37.5665,lng:126.7378,label:'인천 계양구 중심 (핀으로 정확한 건물을 선택하세요)',verified:false};
  const fallback=locationCoords(cleaned),safe=allowed(+fallback[0],+fallback[1])?fallback:[37.4563,126.7052];return{lat:+safe[0],lng:+safe[1],label:'정확한 주소 후보를 찾지 못했습니다. 지도 핀을 옮겨주세요.',verified:false};
};
if(!$('#pickNewPlaceLocation')){$('#newPlaceForm [name=area]').closest('label').insertAdjacentHTML('afterend','<button type="button" id="pickNewPlaceLocation" class="secondary location-picker">지도에서 정확한 위치 선택</button><small id="newPlaceLocationHelp" class="form-note">주소 검색 후 핀을 실제 건물로 옮길 수 있어요.</small>');document.body.insertAdjacentHTML('beforeend','<div id="newPlaceCorrection"><b>가게 건물로 핀을 옮겨주세요</b><button id="applyNewPlacePosition">이 위치 사용</button><button id="cancelNewPlacePosition">취소</button></div>')}
let newPlaceMarker=null;
$('#pickNewPlaceLocation').onclick=async()=>{const form=$('#newPlaceForm'),area=form.elements.area.value.trim();if(!area)return toast('먼저 전체 주소를 입력해주세요.');const loc=await resolveAddress(area);form.dataset.addressLabel=loc.label;$('#newPlaceDialog').close();map.setView([loc.lat,loc.lng],18);if(newPlaceMarker)newPlaceMarker.remove();newPlaceMarker=L.marker([loc.lat,loc.lng],{draggable:true}).addTo(map);$('#newPlaceCorrection').classList.add('show');toast(loc.verified?'주소 후보를 찾았어요. 실제 건물인지 확인해주세요.':'주소 후보가 불확실해요. 핀을 실제 건물로 옮겨주세요.')};
$('#applyNewPlacePosition').onclick=()=>{const form=$('#newPlaceForm'),v=newPlaceMarker.getLatLng();form.dataset.pickedLat=v.lat;form.dataset.pickedLng=v.lng;$('#newPlaceLocationHelp').textContent=`선택 위치: ${v.lat.toFixed(6)}, ${v.lng.toFixed(6)}`;$('#newPlaceCorrection').classList.remove('show');$('#newPlaceDialog').showModal();toast('선택한 지도 위치를 등록에 반영합니다.')};
$('#cancelNewPlacePosition').onclick=()=>{$('#newPlaceCorrection').classList.remove('show');$('#newPlaceDialog').showModal()};
$('#newPlaceForm').onsubmit=async e=>{e.preventDefault();if(!session)return toast('로그인 후 새 장소를 등록할 수 있어요.');const form=e.target,fd=new FormData(form),f=Object.fromEntries(fd),loc=form.dataset.pickedLat?{lat:+form.dataset.pickedLat,lng:+form.dataset.pickedLng,label:form.dataset.addressLabel||'지도에서 직접 선택',verified:true}:await resolveAddress(f.area);if(!loc.verified&&!form.dataset.pickedLat)return toast('주소 후보가 불확실합니다. “지도에서 정확한 위치 선택”으로 건물을 지정해주세요.');const names=fd.getAll('menuName'),prices=fd.getAll('menuPrice'),menus=[];for(let i=0;i<names.length;i++)if(names[i])menus.push([names[i],prices[i]||'가격 문의','']);const p={id:crypto.randomUUID(),createdBy:session.id,name:f.name,type:f.type,area:f.area,resolvedAddress:loc.label,image:await resizeImage(fd.get('imageFile')),visitorGallery:await resizeMany(fd.getAll('galleryFiles').filter(x=>x.size)),ownerGallery:[],lat:loc.lat,lng:loc.lng,desc:'이용자가 새로 등록한 장소',hours:f.open24?'24시간 운영':'정보 확인 중',menus,reviews:f.review?[f.review]:[],quietTimes:[],featureVotes:{},featureVoters:{},reservable:false,acceptingReservations:false};Object.keys(featureLabels).forEach(k=>{p[k]=!!f[k];if(p[k])addVote(p,k,session.id)});places.push(p);store.set('places',places);form.reset();delete form.dataset.pickedLat;delete form.dataset.pickedLng;populatePlaces();render();$('#newPlaceDialog').close();map.setView([p.lat,p.lng],17);toast('선택한 건물 위치에 새 장소를 등록했어요.')};
function deleteMyPlace(id){const p=places.find(x=>x.id===id);if(!p||p.createdBy!==session?.id)return toast('본인이 등록한 가게만 삭제할 수 있어요.');if(!confirm(`“${p.name}”을 지도에서 삭제할까요?`))return;places=places.filter(x=>x.id!==id);store.set('places',places);populatePlaces();render();renderUserAccount();toast('등록한 가게를 삭제했어요.')}
const renderUserAccountV5=renderUserAccount;renderUserAccount=function(){renderUserAccountV5();const mine=places.filter(p=>p.createdBy===session?.id),box=$('#accountSummary');box.insertAdjacentHTML('beforeend',`<h3>내가 등록한 가게</h3><div class="my-places">${mine.length?mine.map(p=>`<div><span><b>${p.name}</b><small>${p.area}</small></span><button onclick="deleteMyPlace('${p.id}')">삭제</button></div>`).join(''):'<small>직접 등록한 가게가 없어요.</small>'}</div>`)};
if(!$('#importOsmPlaces'))$('#locateMe').insertAdjacentHTML('afterend','<button class="location-btn" id="importOsmPlaces" title="현재 지도 주변 카페·식당 불러오기">⌁ 주변 가게</button>');
$('#importOsmPlaces').onclick=async()=>{const button=$('#importOsmPlaces'),c=map.getCenter();button.disabled=true;button.textContent='불러오는 중…';try{const query=`[out:json][timeout:20];(nwr["amenity"~"^(cafe|restaurant)$"](around:2500,${c.lat},${c.lng}););out center tags 60;`,response=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:query}),data=await response.json();let added=0;for(const item of data.elements||[]){const t=item.tags||{},lat=item.lat||item.center?.lat,lng=item.lon||item.center?.lon,id=`osm-${item.type}-${item.id}`;if(!t.name||!lat||!lng||places.some(p=>p.id===id))continue;places.push({id,name:t.name,type:t.amenity==='restaurant'?'food':'cafe',area:[t['addr:city'],t['addr:street'],t['addr:housenumber']].filter(Boolean).join(' ')||'주소 정보 보완 필요',lat,lng,image:'',ownerGallery:[],visitorGallery:[],desc:'OpenStreetMap에서 불러온 장소 · 상세 정보 확인 필요',hours:t.opening_hours||'영업시간 정보 없음',menus:[],reviews:[],quietTimes:[],featureVotes:{},featureVoters:{},reservable:false,source:'OpenStreetMap'});added++}store.set('places',places);populatePlaces();render();toast(`${added}곳을 불러왔어요. 중복 장소는 제외했습니다.`)}catch(error){toast('주변 가게를 불러오지 못했어요. 잠시 후 다시 시도해주세요.')}finally{button.disabled=false;button.textContent='⌁ 주변 가게'}};
let repairedLegacyLocation=false;places.forEach(p=>{if(/황어로\s*188/.test(p.area||'')&&(p.lat<37.50||p.lat>37.70||p.lng<126.60||p.lng>126.85)){p.lat=37.5785;p.lng=126.7315;p.resolvedAddress='인천 계양구 황어로 188 인근 · 지도에서 정확한 건물 위치를 확인해주세요.';repairedLegacyLocation=true}});if(repairedLegacyLocation)store.set('places',places);
window.deleteMyPlace=deleteMyPlace;render();
